version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=nest_practice
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - db
